### ISSUE TITLE
How can I resolve NoSuchMethodError?

### ISSUE THREAD

**Issue by metacret** [infochimps-labs/wonderdog#4]
Hi

I am trying to use wonderdog for bulk-indexing with elasticsearch. I am in trouble with the following error message:

java.lang.NoSuchMethodError: org.elasticsearch.client.IndicesAdminClient.prepareCreate(Ljava/lang/String;)Lorg/elasticsearch/client/action/admin/indices/create/CreateIndexRequestBuilder;
    at com.infochimps.elasticsearch.ElasticSearchOutputFormat$ElasticSearchRecordWriter.initialize_index(ElasticSearchOutputFormat.java:243)
    at com.infochimps.elasticsearch.ElasticSearchOutputFormat$ElasticSearchRecordWriter.<init>(ElasticSearchOutputFormat.java:137)
    at com.infochimps.elasticsearch.ElasticSearchOutputFormat.getRecordWriter(ElasticSearchOutputFormat.java:262)
    at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.<init>(MapTask.java:628)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:753)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:370)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:212)
12/06/13 17:05:23 INFO mapred.JobClient: Job complete: job_local_0001
12/06/13 17:05:23 INFO mapred.JobClient: Counters: 0

Thank you!

**Comment by ghost** [comment]
Running into the same, and see that @rjurney did so as well (https://en.twitter.com/rjurney/status/180784286444683264) - but haven't seen a solution... Any idea what's going on here? I'm on trunk, by the way (wonderdog, elasticsearch, and pig - hadoop is 0.20.205).

**Comment by metacret** [comment]
Don't rely on the wonderdog package. Just copy and paste wonderdog source codes into your project. Then it will work perfectly. I don't know why the wonderdog package didn't work but that's why I closed this issue two months ago.

**Comment by jgagnon1** [comment]
What do you mean by copying the source code into the project ? I'm not sure I understand fully what you mean by that ?

**Comment by jgagnon1** [comment]
I resolved it that way; https://github.com/infochimps-labs/wonderdog/pull/12
